update version and sha
AnacondaRecipes/mkl_random-feedstock pull request #7
Opened 2024-08-29 16:28 UTC by JamesRobertsonGames

{package} {version} {:snowflake:}

**Destination channel:** {Snowflake | defaults}

### Links

- [{ticket_number}]() 
- [Upstream repository]()
- [Upstream changelog/diff]()
- Relevant dependency PRs:
  - ...

### Explanation of changes:

- ...

2024-08-29 16:28 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_d57_1473z7/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:22: cython_needs_compiler: Cython generates C code, which will need to be compiled
- clone/recipe/meta.yaml:33: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
2 Errors and 0 Warnings were found

</details>

2024-08-30 07:51 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_08mvv6cb6l/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:34: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
- clone/recipe/meta.yaml:23: cython_needs_compiler: Cython generates C code, which will need to be compiled
===== Final Report: =====
2 Errors and 0 Warnings were found

</details>

2024-08-30 08:05 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_97r2d79nqz/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:35: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-30 13:18 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_347w9840kh/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.

===== ERRORS =====
- clone/recipe/meta.yaml:40: missing_pip_check: For pypi packages, pip check should be present in the test commands
- clone/recipe/meta.yaml:35: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
2 Errors and 1 Warning were found

</details>

2024-08-30 13:21 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_8723n40gsj/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.

===== ERRORS =====
- clone/recipe/meta.yaml:35: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
1 Error and 1 Warning were found

</details>

2024-08-30 13:44 UTC, JeanChristopheMorinPerso requested changes

2024-08-30 13:44 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - numpy-base >=1.16
```suggestion
    - numpy-base {{ numpy }}
```
mkl_random uses the numpy C API. We have to sue the pinning from aggregate's CBC file.

2024-08-30 13:51 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_53357lje0t/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:35: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-30 14:02 UTC, skupr-anaconda commented on recipe/meta.yaml
> +  skip: True  # [py<39 or py>=313]
I don't think the Python 3.7 has been dropped, see https://github.com/IntelPython/mkl_random/blob/v1.2.7/setup.py#L147. But it's true that their CI builds only py39-py312

2024-08-30 14:14 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_24x6tnj9bq/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:35: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-30 14:22 UTC, JamesRobertsonGames commented
Just want to make sure about one thing during this review, when changing

numpy-base {{ numpy }}

to 

numpy-base >=1.17

It'll build with 2.0.0 base, which inevitably is what I need for numpy 2.0.0 build on 64 bit platforms, using `numpy-base {{ numpy }}` which is what it once was, it avoids 2.0.0. Should I change anything to ensure that 2.0.0 is being built or is the current implementation okay for what I need

2024-08-30 14:26 UTC, cbouss reviewed
This version is to add support for numpy 2.
I would set `skip: True # [py<39]` as there will be no numpy 2 for lower than 3.8 and below and no change in mk_random that justify an update.
Then `numpy-base 2` in host. Then replace pin_compatible in run (which was ineffective due to numpy not being in host) by `numpy >=1.16` to follow upstream. 

Note that the cf recipe is by mkl_random maintainer: https://github.com/conda-forge/mkl_random-feedstock

2024-08-30 14:26 UTC, cbouss commented
> Just want to make sure about one thing during this review, when changing
> 
> numpy-base {{ numpy }}
> 
> to
> 
> numpy-base >=1.17
> 
> It'll build with 2.0.0 base, which inevitably is what I need for numpy 2.0.0 build on 64 bit platforms, using `numpy-base {{ numpy }}` which is what it once was, it avoids 2.0.0. Should I change anything to ensure that 2.0.0 is being built or is the current implementation okay for what I need

Yes we need to build with numpy 2

2024-08-30 14:28 UTC, JamesRobertsonGames commented
Thanks @cbouss ! Wasn't sure about the logistics for specific version builds when to allow the solver to have its way. Will make those changes now

2024-08-30 14:37 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_11ubu2132l/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:35: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-30 14:38 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_8e4f2y4x7h/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:35: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-30 14:45 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_d8rkjnr64x/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:36: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-30 15:01 UTC, cbouss commented on recipe/meta.yaml
> +    - numpy >=1.16
```suggestion
```
You cannot have numpy here due to the cyclic dependency.

2024-08-30 15:01 UTC, cbouss commented on recipe/meta.yaml
> +    - numpy
```suggestion
    - numpy >=1.16
```
To match upstream.

2024-08-30 15:02 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_cc1q3meyce/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:35: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-30 15:44 UTC, JamesRobertsonGames commented
Seems like when the numpy (not base) version is pinned to a lower bound it gets this on osx 

```
conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: {MatchSpec("mkl-devel==2023.1.0=h0e174c6_43559"), MatchSpec("blas=[build=mkl]")}
30 August 2024,04:03:05 	prefect.build	INFO	    Encountered problems while solving:
30 August 2024,04:03:05 	prefect.build	INFO	      - package mkl-devel-2023.1.0-h0e174c6_43559 requires blas * mkl, but none of the providers can be installed
30 August 2024,04:03:05 	prefect.build	INFO	
30 August 2024,04:03:05 	prefect.build	INFO	    Could not solve for environment specs
30 August 2024,04:03:05 	prefect.build	INFO	    The following packages are incompatible
30 August 2024,04:03:05 	prefect.build	INFO	    ├─ mkl-devel 2023.*  is installable and it requires
30 August 2024,04:03:05 	prefect.build	INFO	    │  └─ blas * mkl, which can be installed;
30 August 2024,04:03:05 	prefect.build	INFO	    └─ numpy-base 2.0.0.*  is not installable because it requires
30 August 2024,04:03:05 	prefect.build	INFO	       └─ blas * openblas, which conflicts with any installable versions previously reported.
```

And advice on how to remedy a dependency issue like this?

2024-08-30 16:46 UTC, cbouss commented
> Seems like when the numpy (not base) version is pinned to a lower bound it gets this on osx 
> 
> ```
> conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: {MatchSpec("mkl-devel==2023.1.0=h0e174c6_43559"), MatchSpec("blas=[build=mkl]")}
> 30 August 2024,04:03:05 	prefect.build	INFO	    Encountered problems while solving:
> 30 August 2024,04:03:05 	prefect.build	INFO	      - package mkl-devel-2023.1.0-h0e174c6_43559 requires blas * mkl, but none of the providers can be installed
> 30 August 2024,04:03:05 	prefect.build	INFO	
> 30 August 2024,04:03:05 	prefect.build	INFO	    Could not solve for environment specs
> 30 August 2024,04:03:05 	prefect.build	INFO	    The following packages are incompatible
> 30 August 2024,04:03:05 	prefect.build	INFO	    ├─ mkl-devel 2023.*  is installable and it requires
> 30 August 2024,04:03:05 	prefect.build	INFO	    │  └─ blas * mkl, which can be installed;
> 30 August 2024,04:03:05 	prefect.build	INFO	    └─ numpy-base 2.0.0.*  is not installable because it requires
> 30 August 2024,04:03:05 	prefect.build	INFO	       └─ blas * openblas, which conflicts with any installable versions previously reported.
> ```
> 
> And advice on how to remedy a dependency issue like this?

Oh right, you can skip OSX as we stopped building with mkl there.

2024-08-31 06:17 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_39o1vyar7w/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:34: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-09-02 08:07 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_6bkwz8w1o_/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:35: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-09-02 11:14 UTC, skupr-anaconda approved these changes

2024-09-03 13:28 UTC, cbouss approved these changes

2024-09-03 13:30 UTC, merged

2024-09-03 13:30 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_eaf9ns1vst/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:35: cbc_dep_in_run_missing_from_host: Run dependencies listed in the cbc should also be present in the host section.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>